# Generated by Django 3.1.4 on 2021-01-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='meta',
            field=models.CharField(default='Textmessage', help_text='Type of message sent', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='unread',
            field=models.BooleanField(default=True, help_text='Whether this message has been read or not'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(help_text='message sent through chat message', max_length=255),
        ),
    ]
