name: main-tests

on:
  push:
    branches: [ dev, production]
  pull_request:
    branches: [ dev ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install flake8 pytest coverage Django
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: django tests setup
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: test carespace
        run: |
          python manage.py test carespace
      - name: test joboffer
        run: |
          python manage.py test joboffer
      - name: test user
        run: |
          python manage.py test user
          
